### PR TITLE
Update to platinum-sw 1.2.0

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @tjsavage @addyosmani @ebidel etc.

We'll want to tag a new minor release for this repo following this PR.

### CODE REVIEW

**Comment by ebidel** [comment]
Love it.

**Comment by ebidel** [comment]
Should I be worried about the failing tests?

**Comment by jeffposnick** [comment]
There aren't any tests for this meta-repo, which the CI server treats by default as a failure: http://polymerlabs.github.io/ci-runner/#!/PolymerElements/platinum-elements/1177a02df3a82f5064ee656c3d1a44339d2949bb

(If you're asking about the underlying `<platinum-sw-cache>` test failure on certain browsers, that's being tracked at https://github.com/PolymerElements/platinum-sw/issues/37)

**Comment by ebidel** [comment]
:+1: K

**Pull request merged**
