### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by rictic** [comment]
This repo also has a manually managed README. Blacklisting it too.

**Comment by wibblymat** [comment]
@rictic What would the auto-generated README look like? Our manually managed one is just a basic placeholder, so we might want the auto one anyway.

**Comment by rictic** [comment]
The auto-generated READMEs are based on per-element docs that hydrolysis extracts. e.g. https://github.com/PolymerElements/paper-input/blob/master/README.md

The auto-generator doesn't produce anything useful for repos that just gather up other repos, like paper-elements, iron-elements, platinum-elements, etc.

If there is something that it could generate that would be useful I'd be happy to write it, or if you like you can contribute the cleanup bot, [tedium](https://github.com/polymerlabs/tedium)!

**Comment by wibblymat** [comment]
@rictic Ah, no,got it, didn't spot that this was the collection repo rather than an element.

One possible suggestion would be something like:

This element provides a convenient way to import a collection of other elements:
- [&lt;platinum-sw&gt;](https://elements.polymer-project.org/elements/platinum-sw)
- ...

But it's not particularly important.

**Pull request closed without merging**
